#define _POSIX_C_SOURCE 200809L
#include <errno.h>
#include <sqlite3.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include "sheen/dvr.h"
struct sheen_dvr { sqlite3 *db; };
static uint64_t hash64(const void *data,size_t n,uint64_t h){const unsigned char *p=data;for(size_t i=0;i<n;i++){h^=p[i];h*=1099511628211ULL;}return h;}
static void make_id(const sheen_dvr_job *j,char out[65]){uint64_t h=1469598103934665603ULL;h=hash64(j->channel_id,strlen(j->channel_id),h);h=hash64(&j->start_ms,sizeof(j->start_ms),h);h=hash64(&j->end_ms,sizeof(j->end_ms),h);h=hash64(j->output_path,strlen(j->output_path),h);snprintf(out,65,"%016llx",(unsigned long long)h);}
const char *sheen_dvr_state_name(sheen_dvr_state s){switch(s){case SHEEN_DVR_SCHEDULED:return "scheduled";case SHEEN_DVR_RECORDING:return "recording";case SHEEN_DVR_COMPLETED:return "completed";case SHEEN_DVR_FAILED:return "failed";case SHEEN_DVR_CANCELLED:return "cancelled";}return "unknown";}
sheen_dvr *sheen_dvr_open(const char *path){if(!path)return NULL;sheen_dvr *d=calloc(1,sizeof(*d));if(!d)return NULL;if(sqlite3_open(path,&d->db)!=SQLITE_OK){sqlite3_close(d->db);free(d);return NULL;}return d;}
int sheen_dvr_init(sheen_dvr *d){if(!d||!d->db)return EINVAL;const char *sql="PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS dvr_jobs(recording_id TEXT PRIMARY KEY,channel_id TEXT NOT NULL,title TEXT NOT NULL,output_path TEXT NOT NULL UNIQUE,start_ms INTEGER NOT NULL,end_ms INTEGER NOT NULL,state INTEGER NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL); CREATE INDEX IF NOT EXISTS dvr_due_idx ON dvr_jobs(state,start_ms,end_ms);";return sqlite3_exec(d->db,sql,NULL,NULL,NULL)==SQLITE_OK?0:EIO;}
int sheen_dvr_schedule(sheen_dvr *d,const sheen_dvr_job *in){if(!d||!in||!in->channel_id[0]||!in->output_path[0]||in->end_ms<=in->start_ms)return EINVAL;sheen_dvr_job j=*in;if(!j.recording_id[0])make_id(&j,j.recording_id);j.state=SHEEN_DVR_SCHEDULED;sqlite3_stmt *s=NULL;const char *sql="INSERT INTO dvr_jobs(recording_id,channel_id,title,output_path,start_ms,end_ms,state,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,strftime('%s','now')) ON CONFLICT(recording_id) DO UPDATE SET channel_id=excluded.channel_id,title=excluded.title,output_path=excluded.output_path,start_ms=excluded.start_ms,end_ms=excluded.end_ms,state=excluded.state,updated_at=excluded.updated_at;";if(sqlite3_prepare_v2(d->db,sql,-1,&s,NULL)!=SQLITE_OK)return EIO;sqlite3_bind_text(s,1,j.recording_id,-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,2,j.channel_id,-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,3,j.title,-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,4,j.output_path,-1,SQLITE_TRANSIENT);sqlite3_bind_int64(s,5,j.start_ms);sqlite3_bind_int64(s,6,j.end_ms);sqlite3_bind_int(s,7,j.state);sqlite3_bind_int64(s,8,(sqlite3_int64)time(NULL));int rc=sqlite3_step(s)==SQLITE_DONE?0:EIO;sqlite3_finalize(s);return rc;}
static int fill(sqlite3_stmt *s,sheen_dvr_job *j){memset(j,0,sizeof(*j));snprintf(j->recording_id,sizeof(j->recording_id),"%s",(const char*)sqlite3_column_text(s,0));snprintf(j->channel_id,sizeof(j->channel_id),"%s",(const char*)sqlite3_column_text(s,1));snprintf(j->title,sizeof(j->title),"%s",(const char*)sqlite3_column_text(s,2));snprintf(j->output_path,sizeof(j->output_path),"%s",(const char*)sqlite3_column_text(s,3));j->start_ms=sqlite3_column_int64(s,4);j->end_ms=sqlite3_column_int64(s,5);j->state=(sheen_dvr_state)sqlite3_column_int(s,6);return 0;}
int sheen_dvr_get(sheen_dvr *d,const char *id,sheen_dvr_job *j){if(!d||!id||!j)return EINVAL;sqlite3_stmt *s=NULL;if(sqlite3_prepare_v2(d->db,"SELECT recording_id,channel_id,title,output_path,start_ms,end_ms,state FROM dvr_jobs WHERE recording_id=?;",-1,&s,NULL)!=SQLITE_OK)return EIO;sqlite3_bind_text(s,1,id,-1,SQLITE_TRANSIENT);int rc=sqlite3_step(s);if(rc==SQLITE_ROW)fill(s,j);else rc=ENOENT;sqlite3_finalize(s);return rc==SQLITE_ROW?0:rc;}
int sheen_dvr_list_due(sheen_dvr *d,int64_t now,sheen_dvr_job *jobs,size_t cap,size_t *count){if(!d||!jobs||!count)return EINVAL;*count=0;sqlite3_stmt *s=NULL;if(sqlite3_prepare_v2(d->db,"SELECT recording_id,channel_id,title,output_path,start_ms,end_ms,state FROM dvr_jobs WHERE state=? AND start_ms<=? AND end_ms>? ORDER BY start_ms LIMIT ?;",-1,&s,NULL)!=SQLITE_OK)return EIO;sqlite3_bind_int(s,1,SHEEN_DVR_SCHEDULED);sqlite3_bind_int64(s,2,now);sqlite3_bind_int64(s,3,now);sqlite3_bind_int(s,4,(int)cap);while(*count<cap){int rc=sqlite3_step(s);if(rc!=SQLITE_ROW)break;fill(s,&jobs[(*count)++]);}sqlite3_finalize(s);return 0;}
int sheen_dvr_set_state(sheen_dvr *d,const char *id,sheen_dvr_state st){if(!d||!id)return EINVAL;sqlite3_stmt *s=NULL;if(sqlite3_prepare_v2(d->db,"UPDATE dvr_jobs SET state=?,updated_at=strftime('%s','now') WHERE recording_id=?;",-1,&s,NULL)!=SQLITE_OK)return EIO;sqlite3_bind_int(s,1,st);sqlite3_bind_text(s,2,id,-1,SQLITE_TRANSIENT);int rc=sqlite3_step(s)==SQLITE_DONE?0:EIO;int changed=sqlite3_changes(d->db);sqlite3_finalize(s);return rc?rc:(changed?0:ENOENT);}
int sheen_dvr_cancel(sheen_dvr *d,const char *id){return sheen_dvr_set_state(d,id,SHEEN_DVR_CANCELLED);}
int sheen_dvr_count(sheen_dvr *d,uint64_t *count){if(!d||!count)return EINVAL;sqlite3_stmt *s=NULL;if(sqlite3_prepare_v2(d->db,"SELECT COUNT(*) FROM dvr_jobs;",-1,&s,NULL)!=SQLITE_OK)return EIO;int rc=sqlite3_step(s);if(rc==SQLITE_ROW){*count=(uint64_t)sqlite3_column_int64(s,0);rc=0;}else rc=EIO;sqlite3_finalize(s);return rc;}
void sheen_dvr_close(sheen_dvr *d){if(!d)return;if(d->db)sqlite3_close(d->db);free(d);}
