#include <errno.h>
#include <sqlite3.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "sheen/channel-db.h"
struct sheen_channel_db { sqlite3 *db; };
static uint64_t hash64(const void *data,size_t n,uint64_t h){const unsigned char *p=data;for(size_t i=0;i<n;i++){h^=p[i];h*=1099511628211ULL;}return h;}
static void make_id(const sheen_channel *c,char out[65]){uint64_t h=hash64(&c->service_id,sizeof(c->service_id),1469598103934665603ULL);h=hash64(&c->program_number,sizeof(c->program_number),h);h=hash64(&c->frequency_hz,sizeof(c->frequency_hz),h);h=hash64(c->delivery,strlen(c->delivery),h);snprintf(out,65,"%016llx", (unsigned long long)h);}
struct sheen_channel_db *sheen_channel_db_open(const char *path){if(!path)return NULL;struct sheen_channel_db *d=calloc(1,sizeof(*d));if(!d)return NULL;if(sqlite3_open(path,&d->db)!=SQLITE_OK){sqlite3_close(d->db);free(d);return NULL;}return d;}
int sheen_channel_db_init(sheen_channel_db *d){if(!d||!d->db)return EINVAL;const char *sql="PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS channels(channel_id TEXT PRIMARY KEY,service_id INTEGER NOT NULL,program_number INTEGER NOT NULL,pmt_pid INTEGER NOT NULL,pcr_pid INTEGER NOT NULL,frequency_hz INTEGER NOT NULL,bandwidth_hz INTEGER NOT NULL,delivery TEXT NOT NULL,name TEXT NOT NULL,provider TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 1,UNIQUE(service_id,frequency_hz,delivery)); CREATE INDEX IF NOT EXISTS channels_freq_idx ON channels(frequency_hz,delivery);";return sqlite3_exec(d->db,sql,NULL,NULL,NULL)==SQLITE_OK?0:EIO;}
int sheen_channel_db_upsert(sheen_channel_db *d,const sheen_channel *input){if(!d||!input)return EINVAL;sheen_channel c=*input;if(!c.channel_id[0])make_id(&c,c.channel_id);const char *sql="INSERT INTO channels(channel_id,service_id,program_number,pmt_pid,pcr_pid,frequency_hz,bandwidth_hz,delivery,name,provider,enabled) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(service_id,frequency_hz,delivery) DO UPDATE SET channel_id=excluded.channel_id,program_number=excluded.program_number,pmt_pid=excluded.pmt_pid,pcr_pid=excluded.pcr_pid,bandwidth_hz=excluded.bandwidth_hz,name=excluded.name,provider=excluded.provider,enabled=excluded.enabled;";sqlite3_stmt *s=NULL;if(sqlite3_prepare_v2(d->db,sql,-1,&s,NULL)!=SQLITE_OK)return EIO;sqlite3_bind_text(s,1,c.channel_id,-1,SQLITE_TRANSIENT);sqlite3_bind_int(s,2,c.service_id);sqlite3_bind_int(s,3,c.program_number);sqlite3_bind_int(s,4,c.pmt_pid);sqlite3_bind_int(s,5,c.pcr_pid);sqlite3_bind_int64(s,6,c.frequency_hz);sqlite3_bind_int64(s,7,c.bandwidth_hz);sqlite3_bind_text(s,8,c.delivery,-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,9,c.name,-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,10,c.provider,-1,SQLITE_TRANSIENT);sqlite3_bind_int(s,11,c.enabled);int rc=sqlite3_step(s)==SQLITE_DONE?0:EIO;sqlite3_finalize(s);return rc;}
int sheen_channel_db_count(sheen_channel_db *d,uint64_t *count){if(!d||!count)return EINVAL;sqlite3_stmt *s=NULL;if(sqlite3_prepare_v2(d->db,"SELECT COUNT(*) FROM channels;",-1,&s,NULL)!=SQLITE_OK)return EIO;int rc=sqlite3_step(s)==SQLITE_ROW?0:EIO;if(!rc)*count=(uint64_t)sqlite3_column_int64(s,0);sqlite3_finalize(s);return rc;}
int sheen_channel_db_get(sheen_channel_db *d,const char *id,sheen_channel *c){if(!d||!id||!c)return EINVAL;sqlite3_stmt *s=NULL;if(sqlite3_prepare_v2(d->db,"SELECT channel_id,service_id,program_number,pmt_pid,pcr_pid,frequency_hz,bandwidth_hz,delivery,name,provider,enabled FROM channels WHERE channel_id=?;",-1,&s,NULL)!=SQLITE_OK)return EIO;sqlite3_bind_text(s,1,id,-1,SQLITE_TRANSIENT);int rc=sqlite3_step(s);if(rc!=SQLITE_ROW){sqlite3_finalize(s);return ENOENT;}memset(c,0,sizeof(*c));snprintf(c->channel_id,sizeof(c->channel_id),"%s",(const char*)sqlite3_column_text(s,0));c->service_id=(uint16_t)sqlite3_column_int(s,1);c->program_number=(uint16_t)sqlite3_column_int(s,2);c->pmt_pid=(uint16_t)sqlite3_column_int(s,3);c->pcr_pid=(uint16_t)sqlite3_column_int(s,4);c->frequency_hz=(uint32_t)sqlite3_column_int64(s,5);c->bandwidth_hz=(uint32_t)sqlite3_column_int64(s,6);snprintf(c->delivery,sizeof(c->delivery),"%s",(const char*)sqlite3_column_text(s,7));snprintf(c->name,sizeof(c->name),"%s",(const char*)sqlite3_column_text(s,8));snprintf(c->provider,sizeof(c->provider),"%s",(const char*)sqlite3_column_text(s,9));c->enabled=sqlite3_column_int(s,10);sqlite3_finalize(s);return 0;}
void sheen_channel_db_close(sheen_channel_db *d){if(!d)return;if(d->db)sqlite3_close(d->db);free(d);}
