#define _POSIX_C_SOURCE 200809L
#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <inttypes.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>
#include "sheen/timeshift.h"
typedef struct { uint64_t pts; uint32_t size; uint32_t flags; } rec_hdr;
typedef struct { unsigned index; uint64_t bytes; uint64_t first_pts; uint64_t last_pts; } segment_meta;
struct sheen_timeshift { char dir[4096]; uint64_t max_bytes; uint64_t segment_bytes; uint64_t retained; size_t segment_count; segment_meta *segments; size_t current; int fd; uint64_t read_pts; size_t read_segment; off_t read_offset; int at_edge; };
static int mkdir_p(const char *path){char b[4096];size_t n=strlen(path);if(n>=sizeof(b))return -1;memcpy(b,path,n+1);for(size_t i=1;i<n;i++)if(b[i]=='/'){b[i]=0;if(mkdir(b,0755)<0&&errno!=EEXIST)return -1;b[i]='/';}if(mkdir(b,0755)<0&&errno!=EEXIST)return -1;return 0;}
static int seg_path(const sheen_timeshift *t,unsigned index,char *out,size_t n){int r=snprintf(out,n,"%s/seg-%010u.tsx",t->dir,index);return r<0||(size_t)r>=n?-1:0;}
static int sync_dir(const char *path){int fd=open(path,O_RDONLY|O_DIRECTORY|O_CLOEXEC);if(fd<0)return -1;int r=fsync(fd);close(fd);return r;}
static int load_segments(sheen_timeshift *t){
 DIR *d=opendir(t->dir);if(!d)return errno;struct dirent *e;segment_meta tmp[4096];size_t n=0;
 while((e=readdir(d))&&n<4096){unsigned idx;if(sscanf(e->d_name,"seg-%u.tsx",&idx)!=1)continue;char p[4096];if(seg_path(t,idx,p,sizeof(p))<0)continue;int fd=open(p,O_RDONLY|O_CLOEXEC);if(fd<0)continue;uint64_t bytes=0,first=0,last=0;rec_hdr h;for(;;){ssize_t r=read(fd,&h,sizeof(h));if(r==0)break;if(r!=sizeof(h)){break;}if(!bytes)first=h.pts;last=h.pts;bytes+=sizeof(h)+h.size;if(lseek(fd,h.size,SEEK_CUR)<0)break;}close(fd);if(bytes)tmp[n++]=(segment_meta){idx,bytes,first,last};}
 closedir(d);for(size_t i=0;i<n;i++)for(size_t j=i+1;j<n;j++)if(tmp[j].index<tmp[i].index){segment_meta x=tmp[i];tmp[i]=tmp[j];tmp[j]=x;}t->segments=calloc(n+1,sizeof(*t->segments));if(n&&!t->segments)return ENOMEM;memcpy(t->segments,tmp,n*sizeof(*tmp));t->segment_count=n;t->retained=0;for(size_t i=0;i<n;i++)t->retained+=t->segments[i].bytes;return 0;
}
static int create_current(sheen_timeshift *t){if(t->segment_count==0){t->segments=calloc(1,sizeof(*t->segments));if(!t->segments)return ENOMEM;t->segments[0]=(segment_meta){1,0,0,0};t->segment_count=1;}t->current=t->segment_count-1;char p[4096];if(seg_path(t,t->segments[t->current].index,p,sizeof(p))<0)return ENAMETOOLONG;t->fd=open(p,O_WRONLY|O_APPEND|O_CREAT|O_CLOEXEC,0644);if(t->fd<0)return errno;return 0;}
static int evict_oldest(sheen_timeshift *t){if(t->segment_count<=1)return 0;segment_meta old=t->segments[0];char p[4096];if(seg_path(t,old.index,p,sizeof(p))==0)unlink(p);memmove(t->segments,t->segments+1,(t->segment_count-1)*sizeof(*t->segments));t->segment_count--;t->retained-=old.bytes;if(t->current>0)t->current--;if(t->read_segment>0)t->read_segment--;return 0;}
sheen_timeshift *sheen_timeshift_open(const char *directory,uint64_t max_bytes,uint64_t segment_bytes){if(!directory||!max_bytes||!segment_bytes||segment_bytes>max_bytes)return NULL;sheen_timeshift *t=calloc(1,sizeof(*t));if(!t)return NULL;snprintf(t->dir,sizeof(t->dir),"%s",directory);t->max_bytes=max_bytes;t->segment_bytes=segment_bytes;t->fd=-1;if(mkdir_p(directory)<0){free(t);return NULL;}if(load_segments(t)){sheen_timeshift_close(t);return NULL;}if(create_current(t)){sheen_timeshift_close(t);return NULL;}t->read_segment=t->current;t->read_offset=0;t->at_edge=1;return t;}
int sheen_timeshift_append(sheen_timeshift *t,const void *data,size_t bytes,uint64_t pts){if(!t||t->fd<0||(!data&&bytes)||!bytes)return EINVAL;rec_hdr h={pts,(uint32_t)bytes,0};if(bytes>UINT32_MAX)return EOVERFLOW;uint64_t need=sizeof(h)+bytes;if(t->segments[t->current].bytes&&t->segments[t->current].bytes+need>t->segment_bytes){fsync(t->fd);close(t->fd);t->fd=-1;unsigned next=t->segments[t->current].index+1;segment_meta *p=realloc(t->segments,(t->segment_count+1)*sizeof(*p));if(!p)return ENOMEM;t->segments=p;t->segments[t->segment_count++]=(segment_meta){next,0,pts,pts};t->current=t->segment_count-1;if(create_current(t))return errno;}size_t wrote=0;const unsigned char *p=data;while(wrote<bytes){ssize_t w=write(t->fd,p+wrote,bytes-wrote);if(w<0){if(errno==EINTR)continue;return errno;}if(!w)return EIO;wrote+=(size_t)w;}t->segments[t->current].bytes+=need;if(!t->segments[t->current].first_pts)t->segments[t->current].first_pts=pts;t->segments[t->current].last_pts=pts;t->retained+=need;t->at_edge=1;while(t->retained>t->max_bytes)if(evict_oldest(t))break;fsync(t->fd);return t->retained>t->max_bytes?ENOSPC:0;}
int sheen_timeshift_info_get(sheen_timeshift *t,sheen_timeshift_info *i){if(!t||!i)return EINVAL;memset(i,0,sizeof(*i));if(!t->segment_count)return 0;i->oldest_ms=t->segments[0].first_pts;i->newest_ms=t->segments[t->current].last_pts;i->retained_bytes=t->retained;return 0;}
int sheen_timeshift_seek(sheen_timeshift *t,uint64_t position_ms){if(!t||!t->segment_count)return EINVAL;size_t seg=0;for(size_t i=0;i<t->segment_count;i++)if(t->segments[i].last_pts>=position_ms){seg=i;break;}char p[4096];if(seg_path(t,t->segments[seg].index,p,sizeof(p))<0)return ENAMETOOLONG;int fd=open(p,O_RDONLY|O_CLOEXEC);if(fd<0)return errno;rec_hdr h;off_t off=0;for(;;){ssize_t r=read(fd,&h,sizeof(h));if(r!=sizeof(h))break;if(h.pts>=position_ms){break;}if(lseek(fd,h.size,SEEK_CUR)<0){close(fd);return errno;}off=lseek(fd,0,SEEK_CUR);}close(fd);t->read_segment=seg;t->read_offset=off;t->read_pts=position_ms;t->at_edge=(position_ms>=t->segments[t->current].last_pts);return 0;}
ssize_t sheen_timeshift_read(sheen_timeshift *t,void *data,size_t cap,uint64_t *pts){if(!t||!data||!cap||t->read_segment>=t->segment_count)return -1;for(;;){char p[4096];if(seg_path(t,t->segments[t->read_segment].index,p,sizeof(p))<0)return -1;int fd=open(p,O_RDONLY|O_CLOEXEC);if(fd<0)return -1;if(lseek(fd,t->read_offset,SEEK_SET)<0){close(fd);return -1;}rec_hdr h;ssize_t r=read(fd,&h,sizeof(h));if(r==0){close(fd);if(t->read_segment+1<t->segment_count){t->read_segment++;t->read_offset=0;continue;}t->at_edge=1;return 0;}if(r!=sizeof(h)||h.size>cap){close(fd);return -1;}r=read(fd,data,h.size);close(fd);if(r!=h.size)return -1;t->read_offset+=sizeof(h)+h.size;t->read_pts=h.pts;if(pts)*pts=h.pts;t->at_edge=(t->read_segment==t->current&&t->read_offset>=(off_t)t->segments[t->current].bytes);return r;}}
int sheen_timeshift_at_live_edge(sheen_timeshift *t){return t?t->at_edge:1;}
void sheen_timeshift_close(sheen_timeshift *t){if(!t)return;if(t->fd>=0){fsync(t->fd);close(t->fd);}free(t->segments);free(t);}
