#define _POSIX_C_SOURCE 200809L
#include <errno.h>
#include <netdb.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <sys/socket.h>
#include <unistd.h>
#include "sheen/media-cast.h"
static int split_url(const char *uri,char *host,size_t hn,char *port,size_t pn,char *path,size_t pathn){if(strncmp(uri,"http://",7))return -1;const char *a=uri+7;const char *slash=strchr(a,'/');size_t al=slash?(size_t)(slash-a):strlen(a);if(al>=1024)return -1;char auth[1024];memcpy(auth,a,al);auth[al]=0;char *colon=strrchr(auth,':');if(colon){*colon=0;snprintf(port,pn,"%s",colon+1);}else snprintf(port,pn,"80");snprintf(host,hn,"%s",auth);snprintf(path,pathn,"%s",slash?slash:"/");return 0;}
static int tcp(const char *host,const char *port){struct addrinfo h={0},*r=NULL;h.ai_socktype=SOCK_STREAM;h.ai_family=AF_UNSPEC;if(getaddrinfo(host,port,&h,&r))return -1;int fd=-1;for(struct addrinfo *p=r;p;p=p->ai_next){fd=socket(p->ai_family,p->ai_socktype,p->ai_protocol);if(fd<0)continue;if(connect(fd,p->ai_addr,p->ai_addrlen)==0)break;close(fd);fd=-1;}freeaddrinfo(r);return fd;}
static int http_request(const char *uri,const char *method,const char *headers,const char *body,char *response,size_t cap){char host[1024],port[32],path[4096];if(split_url(uri,host,sizeof(host),port,sizeof(port),path,sizeof(path)))return -1;int fd=tcp(host,port);if(fd<0)return -1;size_t bl=body?strlen(body):0;char req[16384];int n=snprintf(req,sizeof(req),"%s %s HTTP/1.1\r\nHost: %s\r\nConnection: close\r\nContent-Length: %zu\r\n%s\r\n%s",method,path,host,bl,headers?headers:"",body?body:"");if(n<0||(size_t)n>=sizeof(req)){close(fd);return -1;}size_t sent=0;while(sent<(size_t)n){ssize_t w=send(fd,req+sent,n-sent,0);if(w<0){if(errno==EINTR)continue;close(fd);return -1;}sent+=(size_t)w;}size_t got=0;while(got+1<cap){ssize_t r=recv(fd,response+got,cap-got-1,0);if(r<0){if(errno==EINTR)continue;close(fd);return -1;}if(!r)break;got+=(size_t)r;}close(fd);response[got]=0;return got?0:-1;}
static const char *body_part(const char *r){const char *p=strstr(r,"\r\n\r\n");return p?p+4:r;}
static int header_status_ok(const char *r){int code=0;return sscanf(r,"HTTP/%*s %d",&code)==1&&code>=200&&code<300;}
static int soap(const char *control,const char *action,const char *args,char *out,size_t outn){char body[8192];int n=snprintf(body,sizeof(body),"<?xml version=\"1.0\"?><s:Envelope xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\" s:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\"><s:Body><u:%s xmlns:u=\"urn:schemas-upnp-org:service:AVTransport:1\">%s</u:%s></s:Body></s:Envelope>",action,args?action:"",action);if(n<0||(size_t)n>=sizeof(body))return -1;char hdr[512];snprintf(hdr,sizeof(hdr),"Content-Type: text/xml; charset=\"utf-8\"\r\nSOAPAction: \"urn:schemas-upnp-org:service:AVTransport:1#%s\"\r\n",action);if(http_request(control,"POST",hdr,body,out,outn))return -1;return header_status_ok(out)?0:-1;}
int sheen_cast_renderer_describe(const char *location,sheen_cast_renderer *r){if(!location||!r)return EINVAL;memset(r,0,sizeof(*r));snprintf(r->location,sizeof(r->location),"%s",location);char resp[65536];if(http_request(location,"GET","",NULL,resp,sizeof(resp)))return EIO;if(!header_status_ok(resp))return EPROTO;const char *xml=body_part(resp);const char *st=strstr(xml,"urn:schemas-upnp-org:service:AVTransport:1");if(!st)return ENOTSUP;const char *svc=strstr(st,"<service>");if(!svc)svc=xml;const char *cu=strstr(svc,"<controlURL>");if(!cu)return ENOTSUP;cu+=12;const char *end=strstr(cu,"</controlURL>");if(!end)return EPROTO;char rel[2048];size_t n=(size_t)(end-cu);if(n>=sizeof(rel))return EOVERFLOW;memcpy(rel,cu,n);rel[n]=0;if(!strncmp(rel,"http://",7))snprintf(r->control_url,sizeof(r->control_url),"%s",rel);else{char host[1024],port[32],path[4096];if(split_url(location,host,sizeof(host),port,sizeof(port),path,sizeof(path)))return EPROTO;char *last=strrchr(path,'/');if(last)*last=0;char base[4096];snprintf(base,sizeof(base),"http://%s:%s%s/",host,port,path);if(rel[0]=='/')snprintf(r->control_url,sizeof(r->control_url),"http://%s:%s%s",host,port,rel);else snprintf(r->control_url,sizeof(r->control_url),"%s%s",base,rel);}snprintf(r->device_id,sizeof(r->device_id),"%s",location);return 0;}
const char *sheen_cast_media_state_name(sheen_cast_media_state s){switch(s){case SHEEN_CAST_SESSION_CREATED:return "created";case SHEEN_CAST_SESSION_LOADING:return "loading";case SHEEN_CAST_SESSION_PLAYING:return "playing";case SHEEN_CAST_SESSION_STOPPED:return "stopped";case SHEEN_CAST_SESSION_FAILED:return "failed";}return "failed";}
int sheen_cast_media_set_uri(sheen_cast_media_session *s,const char *uri){if(!s||!uri||!s->renderer.control_url[0])return EINVAL;char out[16384];char args[8192];snprintf(args,sizeof(args),"<InstanceID>0</InstanceID><CurrentURI>%s</CurrentURI><CurrentURIMetaData></CurrentURIMetaData>",uri);s->state=SHEEN_CAST_SESSION_LOADING;if(soap(s->renderer.control_url,"SetAVTransportURI",args,out,sizeof(out))){s->state=SHEEN_CAST_SESSION_FAILED;return EIO;}snprintf(s->media_uri,sizeof(s->media_uri),"%s",uri);s->state=SHEEN_CAST_SESSION_CREATED;return 0;}
int sheen_cast_media_play(sheen_cast_media_session *s){if(!s||s->state==SHEEN_CAST_SESSION_FAILED||!s->renderer.control_url[0])return EINVAL;char out[16384];if(soap(s->renderer.control_url,"Play","<InstanceID>0</InstanceID><Speed>1</Speed>",out,sizeof(out))){s->state=SHEEN_CAST_SESSION_FAILED;return EIO;}s->state=SHEEN_CAST_SESSION_PLAYING;return 0;}
int sheen_cast_media_stop(sheen_cast_media_session *s){if(!s||!s->renderer.control_url[0])return EINVAL;char out[16384];if(soap(s->renderer.control_url,"Stop","<InstanceID>0</InstanceID>",out,sizeof(out))){s->state=SHEEN_CAST_SESSION_FAILED;return EIO;}s->state=SHEEN_CAST_SESSION_STOPPED;return 0;}
